package com.src.queries;

public interface ProductQueri {
	String INSERT_QUERY = "INSERT INTO PRODUCT(IDPRODUCT,P_NAME,P_PACKKET,P_ADDRESS,DATES ) VALUES (?,?,?,?,?)";
	String UPDATE_QUERY = "UPDATE PRODUCT SET P_NAME = ? , P_PACKKET = ? , P_ADDRESS=?, DATES=? WHERE IDPRODUCT = ?";
	String DELETE_BY_ID_QUERY = "DELETE FROM PRODUCT WHERE IDPRODUCT = ?";
	String FIND_BY_ID_QUERY = "SELECT * FROM PRODUCT WHERE IDPRODUCT = ?";
	String FIND_ALL_QUERY = "SELECT * FROM PRODUCT";

}
